# Generated by Django 2.0.6 on 2018-09-23 15:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.CharField(blank=True, max_length=1024)),
                ('location', models.CharField(blank=True, max_length=1024)),
                ('agency', models.CharField(blank=True, max_length=1024)),
                ('department', models.CharField(blank=True, max_length=1024)),
                ('telephone', models.CharField(blank=True, max_length=1024)),
                ('skype', models.CharField(blank=True, max_length=1024)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RijpModelBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateField(blank=True, null=True)),
                ('deleted', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('rijpmodelbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='rijp_portal.RijpModelBase')),
                ('name', models.CharField(max_length=256)),
            ],
            bases=('rijp_portal.rijpmodelbase',),
        ),
        migrations.CreateModel(
            name='TestInstance',
            fields=[
                ('rijpmodelbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='rijp_portal.RijpModelBase')),
                ('name', models.CharField(max_length=256)),
            ],
            bases=('rijp_portal.rijpmodelbase',),
        ),
        migrations.CreateModel(
            name='TestTemplate',
            fields=[
                ('rijpmodelbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='rijp_portal.RijpModelBase')),
                ('name', models.CharField(max_length=256)),
            ],
            bases=('rijp_portal.rijpmodelbase',),
        ),
        migrations.AddField(
            model_name='profile',
            name='projects',
            field=models.ManyToManyField(blank=True, related_name='projects', to='rijp_portal.Project'),
        ),
    ]
