# Generated by Django 2.0.6 on 2018-09-30 11:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessDefinition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(choices=[(0, 'Read only'), (1, 'Read and write'), (9, 'Owner')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='RijpModelBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateField(blank=True, null=True)),
                ('deleted', models.DateField(blank=True, null=True)),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='RoleDefinition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('rijpmodelbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='rijp_portal.RijpModelBase')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            bases=('rijp_portal.rijpmodelbase',),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('rijpmodelbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='rijp_portal.RijpModelBase')),
            ],
            bases=('rijp_portal.rijpmodelbase',),
        ),
        migrations.CreateModel(
            name='TestInstance',
            fields=[
                ('rijpmodelbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='rijp_portal.RijpModelBase')),
            ],
            bases=('rijp_portal.rijpmodelbase',),
        ),
        migrations.CreateModel(
            name='TestTemplate',
            fields=[
                ('rijpmodelbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='rijp_portal.RijpModelBase')),
                ('proj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_templates', to='rijp_portal.Project')),
            ],
            bases=('rijp_portal.rijpmodelbase',),
        ),
        migrations.AddField(
            model_name='accessdefinition',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_definitions', to='rijp_portal.RijpModelBase'),
        ),
        migrations.AddField(
            model_name='testinstance',
            name='test_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_instances', to='rijp_portal.TestTemplate'),
        ),
    ]
