# Generated by Django 2.0.6 on 2018-10-06 12:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessDefinition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(choices=[(0, 'Read only'), (1, 'Read and write'), (9, 'Owner')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='RijpModelBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified', models.DateField(default=django.utils.timezone.now)),
                ('is_archived', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=1024)),
                ('priority', models.IntegerField(choices=[(0, 'Ultra low'), (1, 'Low'), (2, 'Medium'), (3, 'High'), (4, 'Immediate')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='RoleDefinition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('rijpmodelbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='rijp_portal.RijpModelBase')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            bases=('rijp_portal.rijpmodelbase',),
        ),
        migrations.CreateModel(
            name='RijpProject',
            fields=[
                ('rijpmodelbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='rijp_portal.RijpModelBase')),
            ],
            bases=('rijp_portal.rijpmodelbase',),
        ),
        migrations.CreateModel(
            name='RijpTestCaseBase',
            fields=[
                ('rijpmodelbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='rijp_portal.RijpModelBase')),
                ('prerequisites', models.CharField(max_length=1024)),
                ('procedure', models.CharField(max_length=1024)),
                ('data', models.CharField(max_length=1024)),
                ('expected_result', models.CharField(max_length=1024)),
                ('status', models.IntegerField(choices=[(0, 'Not executed'), (1, 'Pass'), (2, 'Fail'), (3, 'Blocked')], default=0)),
                ('remarks', models.CharField(max_length=1024)),
                ('test_environment', models.CharField(max_length=1024)),
            ],
            bases=('rijp_portal.rijpmodelbase',),
        ),
        migrations.CreateModel(
            name='RijpTestInstance',
            fields=[
                ('rijpmodelbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='rijp_portal.RijpModelBase')),
            ],
            bases=('rijp_portal.rijpmodelbase',),
        ),
        migrations.CreateModel(
            name='RijpTestTemplate',
            fields=[
                ('rijpmodelbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='rijp_portal.RijpModelBase')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_templates', to='rijp_portal.RijpProject')),
            ],
            bases=('rijp_portal.rijpmodelbase',),
        ),
        migrations.AddField(
            model_name='accessdefinition',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_definitions', to='rijp_portal.RijpModelBase'),
        ),
        migrations.CreateModel(
            name='RijpTestCaseInstance',
            fields=[
                ('rijptestcasebase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='rijp_portal.RijpTestCaseBase')),
                ('execution_timestamp', models.DateTimeField()),
                ('actual_result', models.CharField(max_length=1024)),
            ],
            bases=('rijp_portal.rijptestcasebase',),
        ),
        migrations.CreateModel(
            name='RijpTestCaseTemplate',
            fields=[
                ('rijptestcasebase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='rijp_portal.RijpTestCaseBase')),
                ('test_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_case_templates', to='rijp_portal.RijpTestTemplate')),
            ],
            bases=('rijp_portal.rijptestcasebase',),
        ),
        migrations.AddField(
            model_name='rijptestinstance',
            name='test_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_instances', to='rijp_portal.RijpTestTemplate'),
        ),
        migrations.AddField(
            model_name='rijptestcaseinstance',
            name='test_instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_case_instances', to='rijp_portal.RijpTestInstance'),
        ),
    ]
